Models/Beer.cs
using System.ComponentModel.DataAnnotations;

namespace Backend_Task03.Models
{
    public class Beer
    {
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
		[Required]
		public string Description { get; set; }
        [Required]
        public string Type { get; set; }
        [Required]
        public double? Percentage { get; set; }
        [Required]
        public string Brewery { get; set; }
        [Required]
        public string Country { get; set; }
		[RegularExpression("^[0-9]+$", ErrorMessage = "Only numbers are allowed.")]
		public string EAN13 { get; set; }
        public string? GoesWellWith { get; set; } = "-";
        public double? Rating { get; set; }
        public List<Review>? Reviews { get; set; }
		public List<Account>? FavoritedBy { get; set; }
		public string? PhotoPath { get; set; }
	}
}

Pages/Accounts/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Backend_Task03.Data;
using Backend_Task03.Models;

namespace Backend_Task03.Pages.Accounts
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext database;

        public CreateModel(AppDbContext context)
        {
            database = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Account Account { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || database.Accounts == null || Account == null)
            {
                return Page();
            }

            database.Accounts.Add(Account);
            await database.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Accounts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Backend_Task03.Data;
using Backend_Task03.Models;
using System.Security.Principal;

namespace Backend_Task03.Pages.Accounts
{
	public class DetailsModel : PageModel
	{
		private readonly AppDbContext database;

		[BindProperty]
		public Beer Beer { get; set; } = default!;

		[BindProperty]
		public Account Account { get; set; } = default!;

		public List<Review> AccountReviews { get; set; } = new List<Review>();

		public DetailsModel(AppDbContext context)
		{
			database = context;
		}

		/*		public Account Account { get; set; } = default!;
		*/

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (id == null || database.Accounts == null)
			{
				return NotFound();
			}

			var account = await database.Accounts.Include(a => a.Reviews).ThenInclude(a => a.Beer).FirstOrDefaultAsync(m => m.ID == id);

			if (account == null)
			{
				return NotFound();
			}

			else
			{
				Account = account;
				AccountReviews = account.Reviews.ToList();
			}

			return Page();
		}

		public async Task<IActionResult> OnPostDeleteAsync(int id)
		{
			var review = await database.Reviews.FindAsync(id);

			if (review != null)
			{
				if (review != null)
				{
					database.Reviews.Remove(review);
					await database.SaveChangesAsync();
				}
			}
			string refererUrl = Request.Headers["Referer"].ToString();
			return Redirect(refererUrl);
		}
	}
}

Pages/Beers/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Backend_Task03.Data;
using Backend_Task03.Models;
using Backend_Task03.Utilities;

namespace Backend_Task03.Pages.Beers
{
    public class CreateModel : PageModel
    {
        private readonly Backend_Task03.Data.AppDbContext database;

        public CreateModel(Backend_Task03.Data.AppDbContext context)
        {
            database = context;
        }

        [BindProperty]
        public Beer Beer { get; set; } = default!;

        public IActionResult OnGet(bool generateEAN13 = false)
        {
            Beer = new Beer { EAN13 = EAN13.GenerateEAN13() };
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(IFormFile photo)
        {
            if (!ModelState.IsValid || database.Beers == null || Beer == null)
            {
                return Page();
            }
            var fileName = Guid.NewGuid().ToString() + Path.GetExtension(photo.FileName);
            var filePath = Path.Combine("wwwroot", "imagesBeerly", fileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                await photo.CopyToAsync(fileStream);
            }

            TempData["PhotoPath"] = "/imagesBeerly/" + fileName;

            if (TempData["PhotoPath"] != null)
            {
                Beer.PhotoPath = TempData["PhotoPath"].ToString();
            }

            Beer.EAN13 = EAN13.GenerateEAN13();
            database.Beers.Add(Beer);
            await database.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Beers/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Backend_Task03.Data;
using Backend_Task03.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore.Storage;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Backend_Task03.Pages.Beers
{
	public class DetailsModel : PageModel
	{
		private readonly AppDbContext database;
		private readonly AccessControl accessControl;

		public DetailsModel(AppDbContext context, IHttpContextAccessor httpContextAccessor)
		{
			database = context;
			accessControl = new AccessControl(database, httpContextAccessor);
		}

		public Beer Beer { get; set; } = default!;
		public Review NewReview { get; set; }
		public Account Account { get; set; }

		[BindProperty]
		public List<string> ThisReviewFoodCategories { get; set; } = new List<string>();

		public void LoadBeer(int id)
		{
			Beer = database.Beers
				.Include(b => b.Reviews).ThenInclude(b => b.Account)
				.FirstOrDefault(b => b.ID == id);

			if (Beer == null)
			{
				return;
			}

			if (Beer.Reviews == null)
			{
				Beer.Reviews = new List<Review>();
			}

			NewReview = new Review
			{
				Beer = Beer,
				//oklart om denna ska ligga här
				FoodCategories = new List<FoodCategory>()
			};
		}

		public void ActiveAccount()
		{
			Account = accessControl.LoggedInAccount;
		}

		public IActionResult OnGet(int id)
		{
			Beer = database.Beers
			   .Include(b => b.Reviews).ThenInclude(r => r.FoodCategories)
			   .FirstOrDefault(b => b.ID == id);

			if (Beer.Reviews.Any())
			{
				decimal ratingValueCount = 0;
				decimal reviewCount = 0;

				Dictionary<string, int> categoryCounts = new Dictionary<string, int>();

				// Count the number of times each category appears in the reviews
				foreach (var review in Beer.Reviews)
				{
					foreach (var category in review.FoodCategories)
					{
						if (categoryCounts.ContainsKey(category.Name))
						{
							categoryCounts[category.Name]++;
						}
						else
						{
							categoryCounts[category.Name] = 1;
						}
					}

					if (review.Rating != 0)
					{
						ratingValueCount += review.Rating;
						reviewCount++;
					}
				}

				// Find the category/categories with the highest count
				List<string> mostSelectedCategories = new List<string>();
				int highestCount = 0;
				foreach (var kvp in categoryCounts)
				{
					if (kvp.Value > highestCount)
					{
						mostSelectedCategories.Clear();
						mostSelectedCategories.Add(kvp.Key);
						highestCount = kvp.Value;
					}
					else if (kvp.Value == highestCount)
					{
						mostSelectedCategories.Add(kvp.Key);
					}
				}

				// Update the Rating property
				decimal totalRating = Math.Round(ratingValueCount / reviewCount, 1);
				Beer.Rating = (double)totalRating;

				// Update the GoesWellWith property
				Beer.GoesWellWith = string.Join(", ", mostSelectedCategories);

				database.SaveChanges();
			}

			LoadBeer(id);
			return Page();
		}

		public async Task<IActionResult> OnPostAsync(int id, string? comment, int rating, List<string> food)
		{
			LoadBeer(id);
			ActiveAccount();

			NewReview.Comment = comment;
			NewReview.Rating = rating;
			NewReview.Account = Account;

			foreach (var selectedFood in new[] { "Chicken", "Meat", "Fish", "Vegetarian", "Dessert" })
			{
				if (food.Contains(selectedFood))
				{
					var foodCategory = database.FoodCategories.FirstOrDefault(c => c.Name == selectedFood);
					NewReview.FoodCategories.Add(foodCategory);
					ThisReviewFoodCategories.Add(selectedFood);
				}
			}

			bool success = await TryUpdateModelAsync(
					NewReview,
					nameof(NewReview),
					c => c.Rating,
					c => c.Comment
				);

			if (success)
			{
				Beer.Reviews.Add(NewReview);
				database.Reviews.Add(NewReview);
				database.SaveChanges();
				return RedirectToPage("./Details", new { id = Beer.ID, name = Beer.Name });
			}

			else
			{
				return Page();
			}
		}
		public async Task<IActionResult> OnPostToggleFavoriteAsync(int beerId)
		{
			var beer = database.Beers.Include(b => b.FavoritedBy).FirstOrDefault(b => b.ID == beerId);
			var account = accessControl.LoggedInAccount;

			if (beer != null && account != null)
			{
				if (account.FavoriteBeers.Any(b => b.ID == beerId))
				{
					account.FavoriteBeers.Remove(beer);
					beer.FavoritedBy.Remove(account);
				}
				else
				{
					account.FavoriteBeers.Add(beer);
					beer.FavoritedBy.Add(account);
				}

				await database.SaveChangesAsync();
			}

			return RedirectToPage(new { id = beerId, name = beer.Name });

		}
		public bool IsFavorite(int beerId)
		{
			var account = accessControl.LoggedInAccount;
			return account != null && account.FavoriteBeers.Any(b => b.ID == beerId);
		}

	}
}

Pages/Beers/Edit2.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend_Task03.Data;
using Backend_Task03.Models;

namespace Backend_Task03.Pages.Beers
{
    public class Edit2Model : PageModel
    {
        private readonly AppDbContext database;

        public Edit2Model(AppDbContext context)
        {
            database = context;
        }

        [BindProperty]
        public Beer Beer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || database.Beers == null)
            {
                return NotFound();
            }

            var beer = await database.Beers.FirstOrDefaultAsync(m => m.ID == id);
            if (beer == null)
            {
                return NotFound();
            }
            Beer = beer;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            database.Attach(Beer).State = EntityState.Modified;

            try
            {
                await database.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BeerExists(Beer.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool BeerExists(int id)
        {
            return (database.Beers?.Any(e => e.ID == id)).GetValueOrDefault();
        }
		public async Task<IActionResult> OnPostDeleteAsync(int id)
		{
			var beer = await database.Beers.FindAsync(id);

			if (beer != null)
			{
				database.Beers.Remove(beer);
				await database.SaveChangesAsync();
			}

			return RedirectToPage("./Index");
		}
		public async Task<IActionResult> OnPostUpdateAsync()
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			database.Attach(Beer).State = EntityState.Modified;

			try
			{
				await database.SaveChangesAsync();
			}
			catch (DbUpdateConcurrencyException)
			{
				if (!BeerExists(Beer.ID))
				{
					return NotFound();
				}
				else
				{
					throw;
				}
			}

			return RedirectToPage("./Index");
		}


	}
}

Pages/Beers/Details.cshtml
@page
@model Backend_Task03.Pages.Beers.DetailsModel
@inject Backend_Task03.Data.AccessControl AccessControl

@{
	ViewData["Title"] = "Details";
}

<script type="module" src="~/js/pizza-search.js" asp-append-version="true" defer></script>

<div id="beerDetailsContainer">
	<div id="beerGrid">
		<div id="beerGridCell">
			<div id="beerGridCellRow1">
				<h3 id="beerGridCellRowName">@Html.DisplayFor(model => model.Beer.Name) (@Html.DisplayFor(model => model.Beer.Country))</h3>
			</div>
			<div id="beerGridCellRow2">
				@Html.DisplayFor(model => model.Beer.Brewery)
			</div>
			<div id="beerGridCellImage">
				@if (Model.Beer.PhotoPath == "")
				{
					<img id="smBeerImage" src="~/imagesBeerly/@(Model.Beer.Name).png" width="100px" />
				}
				else
				{
					<img id="smBeerImage" src="@(Model.Beer.PhotoPath)" width="100px" />
				}
			</div>
			<div id="beerGridCellRow3">
				@Html.DisplayFor(model => model.Beer.Description)
			</div>
			<div id="beerGridCellRow4">
				@Html.DisplayFor(model => model.Beer.Percentage)%
			</div>
			<div id="beerGridCellRow5">
				@Html.DisplayFor(model => model.Beer.Type)
			</div>

			<div class="beerFavoriteCell">
				<form asp-page-handler="ToggleFavorite" method="post">
					<input type="hidden" name="beerId" value="@Model.Beer.ID" />
					<input type="checkbox" id="beer@(Model.Beer.ID)Checkbox" class="beerFavoriteCheckbox visually-hidden" @(Model.IsFavorite(Model.Beer.ID) ? "checked" : "") onchange="this.form.submit()" />
					<label for="beer@(Model.Beer.ID)Checkbox" class="beerFavoriteLabel">
						<span class="unfilledStar">
							<img class="beerlyStar" src="~/imagesBeerly/beerlyStarLH.png" alt="Not Filled Star">
						</span>
						<span class="filledStar">
							<img class="beerlyStar" class="checked" src="~/imagesBeerly/beerlyStarFav.png" alt="Filled Star">
						</span>
					</label>
				</form>

				<script>
					document.addEventListener('DOMContentLoaded', function () {
						const checkboxes = document.querySelectorAll('.beerFavoriteCheckbox');

						checkboxes.forEach(function (checkbox) {
							const label = checkbox.nextElementSibling;

							checkbox.addEventListener('change', function () {
								const starUnselected = label.querySelector('.beerlyStar');
								const starSelected = label.querySelector('.beerlyStar.checked');

								if (checkbox.checked) {
									starUnselected.style.display = 'none';
									starSelected.style.display = 'grid';
								} else {
									starUnselected.style.display = 'grid';
									starSelected.style.display = 'none';
								}
							});
						});
					});
				</script>
			</div>

			<div id="beerGridCellRow6">
				<p id="goesWithFood" hidden>
					@Html.DisplayFor(model=>
					model.Beer.GoesWellWith)
				</p>
				@foreach (var food in new[] { "Chicken", "Meat", "Fish", "Vegetarian", "Dessert" })
				{
					if (Model.Beer.GoesWellWith.Contains(food))
					{
						<img asp-append-version="true" name="Goesw" value="@food" src="../images/@(food.ToLower()).svg" style="width: 22px" />
					}
				}
			</div>

			<div id="beerGridCellRow7">
				<p id="beerGridCellRow7Text">Our users give this beer a rating average of:</p>
				@for (int i = 0; i < 5; i++)
				{
					@if (Model.Beer.Rating != null)
					{
						<img class="row7@($"glass{i + 1}")" asp-append-version="true"
					 src="@($"../images/{(i < Math.Floor((decimal)Model.Beer.Rating) ? "filled" : "empty")}.svg")"
					 style="width: 30px" />

					}
				}
			</div>
		</div>

		<div id="pizzaWithBeer">
			<h3 id="pizzaBeerHead">This pizza goes well with your chosen beer:</h3>
			<div id="recommendation" hidden></div>
			<p id="message" hidden>Unfortunately, no pizzas could be retrieved</p>
		</div>

		<div id="beerCRUDButtons">
			@if (AccessControl.LoggedInAccountRole == "Admin")
			{
				<button type="button" onclick="location.href='@Url.Page("./Edit2", new { id = Model.Beer?.ID,  name = Model.Beer?.Name })'">Edit</button>
			}
			<button type="button" onclick="location.href='@Url.Page("./Index")'">Back to List</button>
		</div>
	</div>

	<div id="beerReviewContainer">
		<div id="beerAddReview">
			<h4>Add a Review</h4>
			<form method="post">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="NewReview.Rating" class="control-label"></label>
					<div>
						<label><input type="radio" name="Rating" value="1" /> 1</label>
						<label><input type="radio" name="Rating" value="2" /> 2</label>
						<label><input type="radio" name="Rating" value="3" /> 3</label>
						<label><input type="radio" name="Rating" value="4" /> 4</label>
						<label><input type="radio" name="Rating" value="5" /> 5</label>
					</div>
				</div>

				<div id="beerAddReviewComment" class="form-group">
					<p><label asp-for="NewReview.Comment" class="control-label"></label></p>
					<textarea asp-for="NewReview.Comment" placeholder="Enter comment..." name="Comment" class="form-control"></textarea>
					<span asp-validation-for="NewReview.Comment" class="text-danger"></span>
				</div>

				<div id="beerAddReviewGoes" class="form-group">
					<p>This beer goes well with:</p>
					<label>
						<input type="checkbox" name="food" value="Meat" />
						<img src="../images/meat.svg" asp-append-version="true" style="width: 22px" />
					</label>

					<label>
						<input type="checkbox" name="food" value="Chicken" />
						<img src="../images/chicken.svg" asp-append-version="true" style="width: 22px" />
					</label>

					<label>
						<input type="checkbox" name="food" value="Fish" />
						<img src="../images/fish.svg" asp-append-version="true" style="width: 22px" />
					</label>

					<label>
						<input type="checkbox" name="food" value="Vegetarian" />
						<img src="../images/vegetarian.svg" asp-append-version="true" style="width: 22px" />
					</label>

					<label>
						<input type="checkbox" name="food" value="Dessert" />
						<img src="../images/dessert.svg" asp-append-version="true" style="width: 22px" />
					</label>
				</div>
				<div class="form-group">
					<input type="submit" value="Post" class="btn btn-primary" id="postButton" />
				</div>
			</form>
		</div>

		<div id="beerReviewCell">
			@if (Model.Beer != null && Model.Beer.Reviews != null && Model.Beer.Reviews.Count > 0)
			{
				var sortedReviews = Model.Beer.Reviews.OrderBy(comment => comment.Created);

				<h4>Reviews</h4>
				@foreach (var comment in sortedReviews)
				{
					@if (@comment.Comment != null && @comment.Rating != 0)
					{
						<div id="reviewGridCell">
							<p>@comment.Account.Name said:</p>
							<em>"@comment.Comment"</em><p> And rated it @comment.Rating / 5!</p>
							<p>@comment.Created.ToString("yyyy-MM-dd HH:mm")</p>
						</div>
					}

					@if (@comment.Comment != null && @comment.Rating == 0)
					{
						<div id="reviewGridCell">
							<p>@comment.Account.Name said:</p>
							<em>"@comment.Comment"</em> About this beer
							<p>@comment.Created.ToString("yyyy-MM-dd HH:mm")</p>
						</div>
					}
					@if (@comment.Comment == null && @comment.Rating != 0)
					{
						<div id="reviewGridCell">
							<h3>@comment.Beer.Name</h3>
							<p>@comment.Account.Name</p>
							<p>Rated @comment.Rating / 5!</p>
							<p>@comment.Created.ToString("yyyy-MM-dd HH:mm")</p>
						</div>
					}
				}
			}

			else
			{
				<p>No reviews yet.</p>
			}
		</div>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Pages/Beers/Edit2.cshtml
@page
@model Backend_Task03.Pages.Beers.Edit2Model

@{
	ViewData["Title"] = "Edit";
}

<body>
	<div class="adminGrid">
		<h1>Edit Beer</h1>

		<div class="editBeerGrid">
			<div class="col-md-4">
				<form method="post" asp-page-handler="Update">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<input type="hidden" asp-for="Beer.ID" />
					<div class="form-group">
						<label asp-for="Beer.Name" class="control-label"></label>
						<input asp-for="Beer.Name" class="form-control" />
						<span asp-validation-for="Beer.Name" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Beer.Description" class="control-label"></label>
						<textarea asp-for="Beer.Description" class="form-control"></textarea>
						<span asp-validation-for="Beer.Description" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Beer.Type" class="control-label"></label>
						<input asp-for="Beer.Type" class="form-control" />
						<span asp-validation-for="Beer.Type" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Beer.Percentage" class="control-label"></label>
						<input asp-for="Beer.Percentage" type="number" min="0" step="0.1" max="15" class="form-control" />
						<span asp-validation-for="Beer.Percentage" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Beer.Brewery" class="control-label"></label>
						<input asp-for="Beer.Brewery" class="form-control" />
						<span asp-validation-for="Beer.Brewery" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Beer.Country" class="control-label"></label>
						<select asp-for="Beer.Country" asp-items="@(new SelectList(Data.SampleData.CountryData))" class="form-control">
						</select>
						<span asp-validation-for="Beer.Country" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Beer.EAN13" class="control-label"></label>
						<input asp-for="Beer.EAN13" class="form-control" />
						<span asp-validation-for="Beer.EAN13" class="text-danger"></span>
					</div>
					<button type="submit" class="btn btn-primary">Update</button>
				</form>
				<form method="post">
					<button type="submit" asp-page-handler="Delete" asp-route-id="@Model.Beer.ID" class="btn btn-danger">Delete</button>
				</form>
				<div>
					<button type="button" onclick="location.href='@Url.Page("Index")'">Back to List</button>
				</div>
			</div>
		</div>
	</div>

</body>
@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Pages/Beers/Index.cshtml
@page
@model Backend_Task03.Pages.Beers.IndexModel
@inject Backend_Task03.Data.AccessControl AccessControl

@{
    ViewData["Title"] = "Beer List";
}

<div id="beerIndex">
    <h1 id="beerHead">Beer</h1>

    @*<p>*@
    <form asp-page="Create" method="get" id="beerCreate">
        @if (AccessControl.LoggedInAccountRole == "Admin")
        {
            <button type="submit" class="btn btn-primary">Create New</button>
        }
    </form>
    @*</p>*@

	@foreach (var item in Model.Beer)
	{
		<div class="beerIndexCell">
			<h3 id="beerName">@Html.DisplayFor(modelItem => item.Name)</h3>

			<p id="beerCountry">(@Html.DisplayFor(modelItem => item.Country))</p>

			<p id="beerBrewery">@Html.DisplayFor(modelItem => item.Brewery)</p>

			<p id="beerPercentage">@Html.DisplayFor(modelItem => item.Percentage)%</p>

            <div id="beerImage">
                @if (item.PhotoPath == "")
                {
                    <img id="smBeerImage" src="~/imagesBeerly/@(item.Name).png" width="100px" />
                }
                else
                {
                    <img id="smBeerImage" src="@(item.PhotoPath)" width="100px" />
                }
            </div>

            <p id="beerType">@Html.DisplayFor(modelItem => item.Type)</p>

            <div id="beerGoesWellWith">
                @*@Html.DisplayFor(modelItem => item.GoesWellWith)*@
                @foreach (var food in new[] { "Chicken", "Meat", "Fish", "Vegetarian", "Dessert" })
                {
                    if (item.GoesWellWith.Contains(food))
                    {
                        <img asp-append-version="true" name="Goesw" value="@food" src="../images/@(food.ToLower()).svg" style="width: 22px" />
                    }
                }
            </div>

            <div id="beerRating">

                @for (int i = 0; i < 5; i++)
                {
                    @if (item.Rating != null)
                    {
                        <img class="@($"glass{i + 1}")" asp-append-version="true"
                        src="@($"images/{(i < Math.Floor((decimal)item.Rating) ? "filled" : "empty")}.svg")"
                             style="width: 30px" />
                    }
                }
            </div>

            <button type="button" id="beerDetailsButton" onclick="location.href='@Url.Page("./Details", new { id = item.ID, name = item.Name })'">Details</button>
            <div id="beerFavoriteCell">
                <div id="beerFavoriteCell">
                    <form asp-page-handler="ToggleFavorite" method="post">
                        <input type="hidden" name="beerId" value="@(item.ID)" />
                        <input type="checkbox" id="@(item.ID)Checkbox" class="beerFavoriteCheckbox visually-hidden" onchange="this.form.submit()" @(Model.IsFavorite(item.ID) ? "checked" : "") />
                        <label for="@(item.ID)Checkbox" class="beerFavoriteLabel">
                            <span class="unfilledStar">
                                <img class="beerlyStar" src="~/imagesBeerly/beerlyStarLH.png" alt="Not Filled Star">
                            </span>
                            <span class="filledStar">
                                <img class="beerlyStar" class="checked" src="~/imagesBeerly/beerlyStarFav.png" alt="Filled Star">
                            </span>
                        </label>
                    </form>
                </div>
            </div>
        </div>

        <script>
            document.addEventListener('DOMContentLoaded', function () {
                const checkboxes = document.querySelectorAll('.beerFavoriteCheckbox');

                checkboxes.forEach(function (checkbox) {
                    const label = checkbox.nextElementSibling;

                    checkbox.addEventListener('change', function () {
                        const starUnselected = label.querySelector('.beerlyStar');
                        const starSelected = label.querySelector('.beerlyStar.checked');

                        if (checkbox.checked) {
                            starUnselected.style.display = 'none';
                            starSelected.style.display = 'grid';
                        } else {
                            starUnselected.style.display = 'grid';
                            starSelected.style.display = 'none';
                        }
                    });
                });
            });
        </script>
    }
</div>